version: "3.8"
services:
  na3s:
    build: .
    image: multithefranky/na3s
    platform: linux/amd64
    container_name: na3s
    network_mode: host
    volumes:
      - "./missions:/arma3/mpmissions"
      - "./configs:/arma3/configs"
      - "./mods:/arma3/mods"
      - "./servermods:/arma3/servermods"
      - "/db:/data/db"
    env_file: .env
    restart: unless-stopped
