name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --tag "na3s:$(date +%s)"

  docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env file
        run: cp .env.example .env
      - name: Build the Docker image
        run: docker compose build
