name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Convert repository name to lower case
        run: echo IMAGE_REPOSITORY="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Registry
        uses: docker/build-push-action@v3
        with:
          repository: ${{ env.IMAGE_REPOSITORY }}/na3s
          tags: multithefranky/na3s:latest
          tag_with_ref: true
          push: true
