name: Release
on:
  push:
    branches:
      - "v*.*.*" # Releases
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run Yarn
        run: yarn
      - name: Run Yarn Build
        run: yarn build
      - name: Run Yarn Test
        run: yarn test
      - name: Run Yarn Lint
        run: yarn lint
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Convert repository name to lower case
        run: echo IMAGE_REPOSITORY="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            multithefranky/na3s
            ghcr.io/${{ github.repository }}
      - name: Publish to Registry
        uses: docker/build-push-action@v3
        with:
          repository: ${{ env.IMAGE_REPOSITORY }}/na3s
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          tag_with_ref: true
          push: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
